# Copied from https://github.com/mt-mods/dreambuilder_game

version: "3.6"

services:
  testserver:
    image: ${ENGINE_IMAGE}

    entrypoint: "luantiserver --config /minetest.conf"
    user: root
    volumes:
      - "./:/root/.minetest/mods/"
      - "./world.mt:/root/.minetest/worlds/world/world.mt"
      - "./minetest.conf:/minetest.conf"
      - "./.REPOS/minetest_game/:/root/.minetest/games/minetest_game/"
      - "world:/root/.minetest/worlds/world"
      - "./nodenames.txt:/root/.minetest/worlds/world/nodenames.txt"


volumes:
  world: {}
